services:
  - type: web
    name: food-finder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false